import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import bcrypt from "bcryptjs";
import "dotenv/config";

// ডাটাবেস পুল তৈরি করা
const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

// অ্যাডাপ্টারসহ প্রিজমা ক্লায়েন্ট ইনিশিয়ালাইজ করা
const prisma = new PrismaClient({ adapter });

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL;
  const adminPassword = process.env.ADMIN_PASSWORD;

  if (!adminEmail || !adminPassword) {
    console.error("Error: ADMIN_EMAIL and ADMIN_PASSWORD must be set in .env");
    process.exit(1);
  }

  const hashedPassword = await bcrypt.hash(adminPassword, 10);

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      name: process.env.ADMIN_NAME || "Super Admin",
      password: hashedPassword,
      role: "ADMIN",
    },
  });

  console.log("Admin user created successfully:", admin.email);

  // ---------- Demo author account ----------
  const authorPassword = await bcrypt.hash("Author@12345", 10);
  const author = await prisma.user.upsert({
    where: { email: "author@techtocheck.com" },
    update: {},
    create: {
      email: "author@techtocheck.com",
      name: "Demo Author",
      password: authorPassword,
      role: "AUTHOR",
    },
  });

  // ---------- Demo regular user ----------
  const userPassword = await bcrypt.hash("User@12345", 10);
  const demoUser = await prisma.user.upsert({
    where: { email: "reader@techtocheck.com" },
    update: {},
    create: {
      email: "reader@techtocheck.com",
      name: "Demo Reader",
      password: userPassword,
      role: "USER",
    },
  });

  // ---------- Demo categories ----------
  const categoryDefs = [
    { name: "Smartphones", slug: "smartphones", displayOrder: 1 },
    { name: "Laptops", slug: "laptops", displayOrder: 2 },
    { name: "Audio", slug: "audio", displayOrder: 3 },
    { name: "Wearables", slug: "wearables", displayOrder: 4 },
  ];
  const categories: Record<string, { id: string }> = {};
  for (const c of categoryDefs) {
    categories[c.slug] = await prisma.category.upsert({
      where: { slug: c.slug },
      update: {},
      create: c,
    });
  }

  // ---------- Demo product ----------
  const phone = await prisma.product.upsert({
    where: { slug: "demo-flagship-phone-x1" },
    update: {},
    create: {
      slug: "demo-flagship-phone-x1",
      name: "Flagship Phone X1",
      brand: "DemoTech",
      categoryId: categories["smartphones"].id,
      shortDescription: "A premium demo flagship phone used to showcase the TechToCheck product system.",
      longDescription:
        "This is placeholder demo content generated by the seed script so the product detail page, admin dashboard, and affiliate/video/expert review sections can be exercised locally without manual data entry.",
      verdict: "A strong all-rounder for its price bracket, held back only by average battery life.",
      thumbnailUrl: "https://placehold.co/600x400?text=Flagship+Phone+X1",
      imageUrls: [
        "https://placehold.co/800x600?text=Front",
        "https://placehold.co/800x600?text=Back",
      ],
      pros: ["Excellent display", "Fast performance", "Great cameras"],
      cons: ["Average battery life", "No expandable storage"],
      price: 899.99,
      originalPrice: 999.99,
      currency: "USD",
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date(),
      seoTitle: "Flagship Phone X1 Review | TechToCheck",
      seoDescription: "Our full review of the Flagship Phone X1, including specs, pros, cons, and where to buy.",
      seoKeywords: ["flagship phone x1", "review", "specs"],
      specifications: {
        create: [
          { groupName: "Display", label: "Screen Size", value: "6.7 inch", displayOrder: 0 },
          { groupName: "Display", label: "Refresh Rate", value: "120Hz", displayOrder: 1 },
          { groupName: "Performance", label: "Chipset", value: "DemoChip 9 Gen 3", displayOrder: 2 },
          { groupName: "Battery", label: "Capacity", value: "4500mAh", displayOrder: 3 },
        ],
      },
      affiliateLinks: {
        create: [
          {
            storeName: "Amazon",
            affiliateUrl: "https://amazon.com/demo-flagship-phone-x1",
            price: 899.99,
            currency: "USD",
            availability: "IN_STOCK",
            displayOrder: 0,
          },
          {
            storeName: "Best Buy",
            affiliateUrl: "https://bestbuy.com/demo-flagship-phone-x1",
            price: 909.99,
            currency: "USD",
            availability: "LIMITED_STOCK",
            displayOrder: 1,
          },
        ],
      },
      videoReviews: {
        create: [
          {
            title: "Our Full Review",
            youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            youtubeId: "dQw4w9WgXcQ",
            reviewerName: "TechToCheck",
            isFeatured: true,
            displayOrder: 0,
          },
        ],
      },
      expertReviews: {
        create: [
          {
            reviewerName: "Demo Reviewer",
            reviewerRole: "Editor, Demo Publication",
            quote: "The camera system is one of the best we've tested this year.",
            rating: 4.5,
            isFeatured: true,
            displayOrder: 0,
          },
        ],
      },
    },
  });

  // Second product, so listing/category/related-product/comparison UI has more than one item to show.
  const laptop = await prisma.product.upsert({
    where: { slug: "demo-ultrabook-pro-14" },
    update: {},
    create: {
      slug: "demo-ultrabook-pro-14",
      name: "UltraBook Pro 14",
      brand: "DemoTech",
      categoryId: categories["laptops"].id,
      shortDescription: "A demo ultra-portable laptop for showcasing the comparison and buying-guide UI.",
      longDescription:
        "Placeholder demo content for a second product, so listing pages, category pages, and related-product sections have more than a single item to render.",
      verdict: "Excellent build quality and battery life, though the port selection is limited.",
      thumbnailUrl: "https://placehold.co/600x400?text=UltraBook+Pro+14",
      imageUrls: ["https://placehold.co/800x600?text=UltraBook"],
      pros: ["Superb battery life", "Premium build", "Bright display"],
      cons: ["Limited ports", "No dedicated GPU"],
      price: 1299,
      originalPrice: 1399,
      currency: "USD",
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date(),
      specifications: {
        create: [
          { groupName: "Display", label: "Screen Size", value: "14 inch", displayOrder: 0 },
          { groupName: "Performance", label: "Processor", value: "DemoCore Ultra 7", displayOrder: 1 },
        ],
      },
      affiliateLinks: {
        create: [
          {
            storeName: "Amazon",
            affiliateUrl: "https://amazon.com/demo-ultrabook-pro-14",
            price: 1299,
            currency: "USD",
            availability: "IN_STOCK",
            displayOrder: 0,
          },
        ],
      },
      relatedTo: { connect: [{ id: phone.id }] },
    },
  });

  // ---------- Demo approved customer review (feeds the homepage "Reader Reviews" section) ----------
  await prisma.review.upsert({
    where: { productId_userId: { productId: phone.id, userId: demoUser.id } },
    update: {},
    create: {
      productId: phone.id,
      userId: demoUser.id,
      rating: 5,
      title: "Exactly as reviewed",
      comment: "Been using it for two weeks now and the review nailed it - the camera really is excellent.",
      status: "APPROVED",
      isFeatured: true,
      isVerified: true,
    },
  });
  await prisma.product.update({
    where: { id: phone.id },
    data: { rating: 5, ratingCount: 1 },
  });

  // ---------- Demo blog posts (published, pending review, and draft) ----------
  const publishedPost = await prisma.blog.upsert({
    where: { slug: "flagship-phone-x1-review" },
    update: {},
    create: {
      slug: "flagship-phone-x1-review",
      title: "Flagship Phone X1: Is It Actually Worth Buying?",
      subTitle: "We spent two weeks with DemoTech's newest flagship. Here's our verdict.",
      tags: ["Smartphones", "Reviews"],
      content: [
        { id: "b1", type: "paragraph", value: "<p>After two weeks of daily use, the Flagship Phone X1 has impressed us in almost every category that matters.</p>" },
        { id: "b2", type: "paragraph", value: "<p>The camera system stands out in particular, producing consistently sharp, well-exposed photos even in mixed lighting.</p>" },
      ],
      status: "PUBLISHED",
      isFeatured: true,
      coverImage: "https://placehold.co/1200x630?text=Flagship+Phone+X1+Review",
      authorId: author.id,
      publishedAt: new Date(),
      products: { connect: [{ id: phone.id }] },
    },
  });

  await prisma.blog.upsert({
    where: { slug: "best-laptops-for-travel" },
    update: {},
    create: {
      slug: "best-laptops-for-travel",
      title: "The Best Laptops for Travel This Year",
      subTitle: "Our picks for lightweight laptops that won't slow you down on the road.",
      tags: ["Laptops", "Buying Guide"],
      content: [
        { id: "b1", type: "paragraph", value: "<p>Traveling with a laptop means balancing weight, battery life, and performance.</p>" },
      ],
      status: "PENDING_REVIEW",
      coverImage: "https://placehold.co/1200x630?text=Best+Travel+Laptops",
      authorId: author.id,
      products: { connect: [{ id: laptop.id }] },
    },
  });

  await prisma.blog.upsert({
    where: { slug: "draft-upcoming-wearables" },
    update: {},
    create: {
      slug: "draft-upcoming-wearables",
      title: "Upcoming Wearables We're Excited About (Draft)",
      tags: ["Wearables"],
      content: [{ id: "b1", type: "paragraph", value: "<p>Work in progress notes on upcoming wearables.</p>" }],
      status: "DRAFT",
      authorId: author.id,
    },
  });

  // ---------- Demo comments ----------
  await prisma.comment.create({
    data: {
      blogId: publishedPost.id,
      userId: demoUser.id,
      content: "Great write-up! Confirms what I was already leaning towards.",
    },
  });
  await prisma.comment.create({
    data: {
      blogId: publishedPost.id,
      guestName: "Guest Reader",
      guestEmail: "guest@example.com",
      content: "How does the battery life compare to last year's model?",
    },
  });

  console.log("Demo users, categories, products, blog posts, reviews, and comments seeded successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end(); // পুল ক্লোজ করা
  });
